### ISSUE TITLE
process of deployment to Github Pages

### ISSUE THREAD

**Issue by tangway** [tangway/flag-guessing-game-frontend#39]

**Comment by tangway** [comment]
decided to follow the guide from https://github.com/sitek94/vite-deploy-demo?tab=readme-ov-file since it has 253 stars and the youtube video for it has many comments saying it works as explained.

ran into error after at the Build step of the job. it couldnt find `package.json` as im using pnpm and the folder where it was trying to find it is doubled like `.../flag-guessing-game-frontend/flag-guessing-game-frontend/package.json`

**Comment by tangway** [comment]
i changed the Build Project part of the file to use `pnpm` instead but that didn't change anything. with hindsight i could see that the step that produced the error is before the Build Project step

decided to try running a manual build myself as i remember doing this before. used `pnpm run build`
noticed that the `dist` folder isn't in my repo so i checked `.gitignore` and commented out the `dist` folder

**Comment by tangway** [comment]
when i ran the command to deploy to Github Pages `gh-pages -d build` it tells me there is no file or folder called `build`. the build folder for Vite projects is `dist` so i changed it to `gh-pages -d dist`.

noticed that `git push` did not trigger a build of the page so on Github Pages settings, i changed the branch where it should build from to `gh-pages` and ran `gh-pages -d build` again.

**Comment by tangway** [comment]
so after im sure that running `gh-pages -d dist` triggers the Pages build process, i check the live site and it's blank. 
the console log's `“https://tangway.github.io/assets/index-kUIlE5N5.js” was blocked because of a disallowed MIME type (“text/html”).`
the url should start with `https://tangway.github.io/flag-guessing-game-frontend/` , so it must be something to do with a reference to the repo being wrong.

besides `package.json`, `vite.config.js` is the only other file which has to reference the repo so i changed the `base` value from `/` to `/flag-guessing-game-frontend/`
```js
export default {
 base: '/flag-guessing-game-frontend/', 
}
```

after this change i ran `pnpm build` and `gh-pages -d dist` again, checked the live site and it worked!

**Comment by tangway** [comment]
changing deploy.yml to these settings worked!
the main thing was finding the right code to setup pnpm. it was found at the readme section for https://github.com/pnpm/action-setup

```yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build
```
